version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
    IMAGE_URI: 786359466063.dkr.ecr.us-east-1.amazonaws.com/eks-devops
    #786359466063.dkr.ecr.us-east-1.amazonaws.com/eks-devops

phases:
  pre_build:
    commands:
    - set -euo pipefail
    - echo "SRC dir: $CODEBUILD_SRC_DIR"
    - ls -la
    - echo "Validate required files/folders exist"
    - test -f Dockerfile || { echo "Dockerfile missing at repo root"; exit 1; }
    - test -d app1 || { echo "app1/ folder missing at repo root"; exit 1; }
    - IMAGE_TAG="$(echo "$CODEBUILD_RESOLVED_SOURCE_VERSION" | cut -c1-7)"
    - export IMAGE_TAG
    - echo "Login to ECR registry"
    - REGISTRY="${IMAGE_URI%/*}" # strip repo name
    - aws ecr get-login-password --region "$AWS_DEFAULT_REGION" | docker login --username AWS --password-stdin "$REGISTRY"
  build:
    commands:
    - echo "Building image $IMAGE_URI:$IMAGE_TAG"
    - docker build -t "$IMAGE_URI:$IMAGE_TAG" .
  post_build:
    commands:
    - echo "Pushing image"
    - docker push "$IMAGE_URI:$IMAGE_TAG"
    # optional handoff artifact for a deploy stage (ECS/CodeDeploy)
    - printf '[{"name":"app","imageUri":"%s"}]' "$IMAGE_URI:$IMAGE_TAG" > imagedefinitions.json
artifacts:
  files:
  - imagedefinitions.json
  - buildspec-deploy.yml
  - 'kube-manifests/**/*'
