version: 0.2
env:
  variables:
    AWS_DEFAULT_REGION: us-east-1
phases:
  pre_build:
    commands:
    - set -euo pipefail
    - source ./exported-vars.env
    - echo "IMAGE_URI=$IMAGE_URI"
    - echo "IMAGE_TAG=$IMAGE_TAG"
    - sed -i 's@CONTAINER_IMAGE@'"$IMAGE_URI:$IMAGE_TAG"'@' kube-manifests/01-DEVOPS-Nginx-Deployment.yml
  build:
    commands:
    - echo "Updating kubeconfig and using role to get token"
    - aws eks update-kubeconfig --region "$AWS_DEFAULT_REGION" \ --name "$EKS_CLUSTER_NAME" \ --role-arn "$EKS_KUBECTL_ROLE_ARN"
    - echo "Sanity auth check:"
    - kubectl auth can-i get pods --all-namespaces
    - echo "Applying manifests"
    - kubectl apply -f kube-manifests/
  post_build:
    commands:
    - echo "Resources:"
    - kubectl get deploy,svc,ing -o wide
